openapi: 3.0.3
info:
  title: 'Mage 8'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://mage8-server.test'
paths:
  /api/v1/auth/google-sign-in:
    post:
      summary: 'Login user and create token using Google access token.'
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: '0'
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 13
                    name: 'Irnanto Gada Firgantoro'
                    email: manah.wijayanti@example.net
                    google_id: 0f4da853-56f7-3e9a-9691-21cb5a748aae
                    image_path: null
                    phone: '0662 5313 607'
                    is_vendor: false
                  message: 'Login Success'
                  token: bearer_token_for_authentication
                properties:
                  data:
                    type: object
                    example:
                      id: 13
                      name: 'Irnanto Gada Firgantoro'
                      email: manah.wijayanti@example.net
                      google_id: 0f4da853-56f7-3e9a-9691-21cb5a748aae
                      image_path: null
                      phone: '0662 5313 607'
                      is_vendor: false
                  message:
                    type: string
                    example: 'Login Success'
                  token:
                    type: string
                    example: bearer_token_for_authentication
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                access_token:
                  type: string
                  description: 'Google access token.'
                  example: aut
                fcm_token:
                  type: string
                  description: 'optional Firebase Cloud Messaging token.'
                  example: quam
                device_name:
                  type: string
                  description: 'Device name the user is using.'
                  example: asperiores
              required:
                - access_token
                - device_name
      security: []
  /api/v1/user:
    get:
      summary: ''
      description: ''
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
tags:
  -
    name: Endpoints
    description: ''
