openapi: 3.0.3
info:
  title: 'Mage 8'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://mage8-server.test'
paths:
  /api/v1/auth/google-sign-in:
    post:
      summary: 'Google SignIn'
      description: 'Login user and create token using Google access token.'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: '0'
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 44
                    name: 'Yusuf Widodo'
                    email: padmasari.samiah@example.org
                    image_url: null
                    phone: '(+62) 565 8263 779'
                    is_vendor: false
                  message: 'Login Success'
                  token: bearer_token_for_authentication
                properties:
                  data:
                    type: object
                    example:
                      id: 44
                      name: 'Yusuf Widodo'
                      email: padmasari.samiah@example.org
                      image_url: null
                      phone: '(+62) 565 8263 779'
                      is_vendor: false
                  message:
                    type: string
                    example: 'Login Success'
                  token:
                    type: string
                    example: bearer_token_for_authentication
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                access_token:
                  type: string
                  description: 'Google access token. Use `debug_token` for debugging (only works in debug mode).'
                  example: debug_token
                fcm_token:
                  type: string
                  description: 'optional Firebase Cloud Messaging token.'
                  example: null
                device_name:
                  type: string
                  description: 'Device name the user is using.'
                  example: Scribe
              required:
                - access_token
                - device_name
      security: []
  /api/v1/auth/user:
    get:
      summary: 'Current User'
      description: 'Get the authenticated user.'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: '0'
          content:
            application/json:
              schema:
                type: object
                example:
                  data:
                    id: 45
                    name: 'Agus Halim S.Gz'
                    email: nugroho.hesti@example.net
                    image_url: null
                    phone: '0979 8998 811'
                    is_vendor: false
                properties:
                  data:
                    type: object
                    example:
                      id: 45
                      name: 'Agus Halim S.Gz'
                      email: nugroho.hesti@example.net
                      image_url: null
                      phone: '0979 8998 811'
                      is_vendor: false
      tags:
        - Endpoints
  /api/v1/auth/logout:
    post:
      summary: Logout
      description: 'Revoke current user token, other token can still be used.'
      parameters:
        -
          in: header
          name: Content-Type
          description: ''
          example: application/json
          schema:
            type: string
        -
          in: header
          name: Accept
          description: ''
          example: application/json
          schema:
            type: string
      responses:
        200:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: 'Logout Success'
                properties:
                  message:
                    type: string
                    example: 'Logout Success'
      tags:
        - Endpoints
tags:
  -
    name: Endpoints
    description: ''
